server:
  port: 8081

spring:
  application:
    name: doctor-service
  datasource:
    url: jdbc:mysql://localhost:3306/DOCTOR_DB
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
    hibernate:
      ddl-auto: update

      eureka:
        client:
          serviceUrl:
            defaultZone: http://localhost:8761/eureka
